name: CI
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        # TODO: python 2.6
        python-version: [3.9]
        python-impl: [cpython]
        ytdl-test-set: [core]
        run-tests-ext: [sh]
        # python 3.2 is only available on windows via setup-python
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      if: ${{ matrix.python-impl == 'cpython' }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Java 8
      if: ${{ matrix.python-impl == 'jython' }}
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install Jython
      if: ${{ matrix.python-impl == 'jython' }}
      run: |
        wget https://repo1.maven.org/maven2/org/python/jython-installer/2.7.1/jython-installer-2.7.1.jar -O jython-installer.jar
        java -jar jython-installer.jar -s -d "$HOME/jython"
        echo "$HOME/jython/bin" >> $GITHUB_PATH
    - name: Install nose
      if: ${{ matrix.python-impl != 'jython' }}
      run: pip install nose
    - name: Install yourbase
      if: ${{ matrix.python-version == 3.9 }}
      run: pip install yourbase; pip install --force-reinstall coverage==6.1; pip install pytest
    - name: Install nose (Jython)
      if: ${{ matrix.python-impl == 'jython' }}
      # Working around deprecation of support for non-SNI clients at PyPI CDN (see https://status.python.org/incidents/hzmjhqsdjqgb)
      run: |
        wget https://files.pythonhosted.org/packages/99/4f/13fb671119e65c4dce97c60e67d3fd9e6f7f809f2b307e2611f4701205cb/nose-1.3.7-py2-none-any.whl
        pip install nose-1.3.7-py2-none-any.whl
    - name: load remote graph to s3 bucket
      env:
        AWS_S3_BUCKET: youtube-dl-test-123
        AWS_ACCESS_KEY_ID: AKIA4YF2YHK3JVVABOT6
        AWS_SECRET_ACCESS_KEY: z5Pz9kuLDOL9dyLMmT3gJrpSiDOy1iJjomaCdKd9
        AWS_DEFAULT_REGION: us-east-1
      run: aws s3 cp --recursive s3://youtube-dl-test-123/python $HOME/yourbase/python
    - name: Run tests
      continue-on-error: ${{ matrix.ytdl-test-set == 'download' || matrix.python-impl == 'jython' }}
      env:
        YTDL_TEST_SET: ${{ matrix.ytdl-test-set }}
        AWS_S3_BUCKET: youtube-dl-test-123
        AWS_ACCESS_KEY_ID: AKIA4YF2YHK3JVVABOT6
        AWS_SECRET_ACCESS_KEY: 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
      run: ./devscripts/run_tests.${{ matrix.run-tests-ext }}
    - name: send remote graph to s3 bucket
      env:
        AWS_S3_BUCKET: youtube-dl-test-123
        AWS_ACCESS_KEY_ID: AKIA4YF2YHK3JVVABOT6
        AWS_SECRET_ACCESS_KEY: z5Pz9kuLDOL9dyLMmT3gJrpSiDOy1iJjomaCdKd9
        AWS_DEFAULT_REGION: us-east-1
      run: aws s3 cp --recursive $HOME/.cache/yourbase s3://youtube-dl-test-123/

  flake8:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      run: flake8 .
