name: GitHub Metrics

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Download and Extract Source Code
      run: |
        curl -L https://cs489.s3.amazonaws.com/git-metrics-master.zip -o code.zip
        unzip code.zip -d git-metrics
    - name: Install Dependencies
      run: |
        pip install -r git-metrics/requirements.txt
    - name: Run Metrics
      run: |
        python git-metrics/git_metrics.py --master-branch=refs/tags/2021.12.17 open-branches .
