name: Build
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install yb
      uses: yourbase/install-yb-action@v1
      with:
        # Pin to a specific version of yb. If omitted, defaults to the latest release.
        version: v0.6.3
    - name: Build
      run: yb build
